### ISSUE TITLE
Binary should be in Releases not Code

### ISSUE THREAD

**Issue by GirkovArpa** [valplusplusle/DavinciLinuxConverter#4]
[davinci-linux-converter-0.1.0.AppImage](https://github.com/valplusplusle/DavinciLinuxConverter/blob/master/davinci-linux-converter-0.1.0.AppImage) belongs in [Releases](https://github.com/valplusplusle/DavinciLinuxConverter/releases) not in the source files.  

Currently it's impossible to run `git clone https://github.com/valplusplusle/DavinciLinuxConverter` without needlessly downloading a `71.5 mb` file.

**Comment by valplusplusle** [comment]
True its an old repo did not maintain it for a while. i take a look at it.

**Comment by valplusplusle** [comment]
fixed on master, maybe if i find the time i write a build script to automatically build a release.
